tambah query berdasarkan kategori
commitunuja/mpnj-web pull request #261
Opened 2020-09-01 13:00 UTC by masbrodev

Issue dari #251 mohon di review @milhamsuryapratama

2020-09-01 13:01 UTC, milhamsuryapratama commented
Oke, lanjut issue yang lain dulu

2020-09-01 14:47 UTC, masbrodev commented
> Oke, lanjut issue yang lain dulu

projekan luh, gantian

2020-09-02 07:20 UTC, milhamsuryapratama requested changes

2020-09-02 07:20 UTC, milhamsuryapratama commented on app/Http/Controllers/Web/ProdukWebController.php
> +            $data['produk'] = Produk::with(['foto_produk', 'kategori', 'user', 'wishlists'])->where('status', 'aktif')->where('nama_produk', 'like', '%' . $nama_produk . '%')->orWhereHas('kategori',
dibagian ini, ada query filter rentan harga yang hilang. jadi untuk pecarian fitur rentan harga tidak berfungsi. coba perbaiki

2020-09-02 14:16 UTC, masbrodev commented on app/Http/Controllers/Web/ProdukWebController.php
> +            $data['produk'] = Produk::with(['foto_produk', 'kategori', 'user', 'wishlists'])->where('status', 'aktif')->where('nama_produk', 'like', '%' . $nama_produk . '%')->orWhereHas('kategori',
test lagi

2020-09-02 14:16 UTC, masbrodev commented
@milhamsuryapratama

2020-09-02 15:49 UTC, milhamsuryapratama commented
Oke, mantap sudah @masbrodev 

Cuma ada beberapa tambahan untuk validasi

- [ ] Validasi rentan harga tidak boleh negatif
- [ ] Rentan harga dari tidak boleh lebih besar dari sampai
- [ ] Kalau bisa kasih event keyup ketika ngetik harga langsung terformat ke rupiah (opsional)

2020-09-02 16:53 UTC, masbrodev reviewed
> Oke, mantap sudah @masbrodev
> 
> Cuma ada beberapa tambahan untuk validasi
> 
> * [ ]  Validasi rentan harga tidak boleh negatif
> * [ ]  Rentan harga dari tidak boleh lebih besar dari sampai
> * [ ]  Kalau bisa kasih event keyup ketika ngetik harga langsung terformat ke rupiah (opsional)

Selebihnya itu tugas Lead sudah

2020-10-20 13:27 UTC, merged